### PR TITLE
Allow setting RGBW pixels with RGB tuples

### PR DESCRIPTION
**Pull request by dunkmann00**
This change mirrors the change made in CP for pixelbuf [#2954](https://github.com/adafruit/circuitpython/pull/2954)

### CODE REVIEW

**Comment by dunkmann00** [comment]
@kattni Have you been able to check this one over?

**Comment by rhooper** [comment]
This looks good, and works.
It might be worth updating the simpletest to exercise this.

```
buf = TestBuf(20, "RGBW", 1.0, auto_write=True)
buf[0] = (1, 2, 3)
buf[1] = (1, 2, 3, 4)
buf[2] = (2, 2, 2)
```
had the expected results.

**Review by rhooper — APPROVED** [review]
These changes look good and work.

**Comment by dunkmann00** [comment]
Sorry for taking so long, but I added the changes @rhooper suggested into simpletest

**Review by rhooper — APPROVED** [review]
Looks great, thanks for making Pypixelbuf behave the same as _pixelbuf!

**Pull request merged**
